serviceName: messaging
httpPort: 9013
grpcPort: 9014
logLevel: -1
security:
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
databases:
- required: true
  type: sqlDatabase
  address: localhost:3306
  user: root
  password: hakty11
  schema: ussd
  metadata:
    name: sqlWrites
    dialect: mysql
    orm: gorm
- required: true
  type: sqlDatabase
  address: localhost:3306
  user: root
  password: hakty11
  schema: ussd
  metadata:
    name: sqlReads
    dialect: mysql
    orm: gorm
externalServices:
- name: call
  required: true
  address: localhost:8080
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: emailing
  required: true
  address: localhost:9015
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: pusher
  required: true
  address: localhost:8060
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: sms
  required: true
  address: localhost:8050
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: subscriber
  required: true
  address: localhost:9060
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost