serviceVersion: v1/beta
serviceName: messaging
servicePort: 6060
logging:
  level: 1
  timeFormat: 2006-01-02T15:04:05Z07:00
security:
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
databases:
  sqlDatabase:
    required: true
    address: localhost:3306
    host: localhost
    port: 3306
    user: root
    password: hakty11
    schema: emrs
    metadata:
      name: mysql
      dialect: mysql
      orm: gorm
  redisDatabase:
    required: true
    address: localhost:6379
    host: localhost
    port: 6379
externalServices:
- name: call
  type: Call
  required: true
  address: localhost:5050
  host: localhost
  port: 5050
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: emailing
  type: Emailing
  required: true
  address: localhost:5040
  host: localhost
  port: 5040
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: pusher
  type: Pusher
  required: true
  address: localhost:5030
  host: localhost
  port: 5030
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: sms
  type: SMS
  required: true
  address: localhost:5020
  host: localhost
  port: 5020
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost