serviceName: emailing
httpPort: 9015
grpcPort: 9016
startupSleepSeconds: 5
logLevel: -1
security:
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost