serviceName: pusher
httpPort: 5030
logLevel: -1
security:
  tlsCert: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost