// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pusher

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PushMessagingClient is the client API for PushMessaging service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushMessagingClient interface {
	// Sends push message
	SendPushMessage(ctx context.Context, in *PushMessage, opts ...grpc.CallOption) (*empty.Empty, error)
}

type pushMessagingClient struct {
	cc grpc.ClientConnInterface
}

func NewPushMessagingClient(cc grpc.ClientConnInterface) PushMessagingClient {
	return &pushMessagingClient{cc}
}

func (c *pushMessagingClient) SendPushMessage(ctx context.Context, in *PushMessage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/gidyon.apis.PushMessaging/SendPushMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushMessagingServer is the server API for PushMessaging service.
// All implementations must embed UnimplementedPushMessagingServer
// for forward compatibility
type PushMessagingServer interface {
	// Sends push message
	SendPushMessage(context.Context, *PushMessage) (*empty.Empty, error)
	mustEmbedUnimplementedPushMessagingServer()
}

// UnimplementedPushMessagingServer must be embedded to have forward compatible implementations.
type UnimplementedPushMessagingServer struct {
}

func (UnimplementedPushMessagingServer) SendPushMessage(context.Context, *PushMessage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendPushMessage not implemented")
}
func (UnimplementedPushMessagingServer) mustEmbedUnimplementedPushMessagingServer() {}

// UnsafePushMessagingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushMessagingServer will
// result in compilation errors.
type UnsafePushMessagingServer interface {
	mustEmbedUnimplementedPushMessagingServer()
}

func RegisterPushMessagingServer(s grpc.ServiceRegistrar, srv PushMessagingServer) {
	s.RegisterService(&_PushMessaging_serviceDesc, srv)
}

func _PushMessaging_SendPushMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushMessagingServer).SendPushMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gidyon.apis.PushMessaging/SendPushMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushMessagingServer).SendPushMessage(ctx, req.(*PushMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _PushMessaging_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gidyon.apis.PushMessaging",
	HandlerType: (*PushMessagingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendPushMessage",
			Handler:    _PushMessaging_SendPushMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pusher.proto",
}
