apiVersion: v1
entries:
  account:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-08T04:31:37.40468+03:00"
    dependencies:
    - name: micro
      repository: https://raw.githubusercontent.com/gidyon/services/master/deployments/helm/charts/micro
      version: 0.1.0
    description: A Helm chart for Kubernetes
    digest: aa74c37b826d56f57eeeb36ead70882ec972449089cc31e0a79fe1fe6632b6d4
    name: account
    type: application
    urls:
    - account-0.1.0.tgz
    version: 0.1.0
  micro:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-08T04:31:37.408633+03:00"
    description: Chart boilerplate for creating micro services
    digest: c0231984e9e45b2ebdcfb0bc8091e70200364e04666aee0e54d2c1acca44763d
    name: micro
    type: library
    urls:
    - micro-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-08T04:31:37.402882+03:00"
