apiVersion: v2
name: subscriber
description: Manages subscriptions, topics and subscribers
type: application
version: 0.1.1
appVersion: 1.16.0

dependencies:
- name: micro
  version: 0.1.0
  repository: "@micro"