serviceVersion: v1/beta
serviceName: account
servicePort: 7070
logging:
  level: 1
  timeFormat: 2006-01-02T15:04:05Z07:00
security:
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
databases:
  sqlDatabase:
    required: true
    address: localhost:3306
    host: localhost
    port: 3306
    user: root
    password: hakty11
    schema: emrs
    metadata:
      name: mysql
      dialect: mysql
      orm: gorm
  redisDatabase:
    required: true
    address: localhost:6379
    host: localhost
    port: 6379
externalServices:
- name: messaging
  type: Messaging
  required: true
  address: localhost:6060
  host: localhost
  port: 6060
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost