apiVersion: v1
kind: ConfigMap
metadata:
  name: subscriber-v1
  labels:
    app: longrunning
data:
  config.yml: |
    serviceName: "Longrunning API"
    httpPort: 80
    startupSleepSeconds: 5
    logLevel: -1
    security:
      insecure: true
    database:
      sqlDatabase:
        required: true
        address: mysql:3306
        user: root
        schema: services
        passwordFile: /app/secrets/mysql/mysql-root-password
        metadata:
          name: mysql
          dialect: mysql
          orm: gorm
    externalServices:
    - name: channel
      required: true
      address: channel:8080
      k8service: true
      insecure: true
    - name: account
      required: true
      address: account:8080
      k8service: true
      insecure: true
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber
  labels:
    app: longrunning
spec:
  selector:
    app: longrunning
  ports:
  - port: 80
    name: http
  - port: 8080
    name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longrunning
  labels:
    app: longrunning
    version: v1
spec:

  replicas: 1
  selector:
    matchLabels:
      app: longrunning
      version: v1
  template:
    metadata:
      labels:
        app: longrunning
        version: v1
    spec:
      containers:
      - name: subscriber
        image: gidyon/subscriber:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          name: grpc
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
          limits:
            cpu: 1000m
            memory: 200Mi
        env:
        - name: API_HASH_KEY
          valueFrom:
            secretKeyRef:
              name: symmetric-keys
              key: api-hash-key
        - name: API_BLOCK_KEY
          valueFrom:
            secretKeyRef:
              name: symmetric-keys
              key: api-block-key
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: symmetric-keys
              key: jwt-signing-key
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /api/longrunning/health/ready
            port: 80
          initialDelaySeconds: 8
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 3
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /api/operations/health/live
            port: 80
          initialDelaySeconds: 8
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 3
        volumeMounts:
          - name: app-config
            mountPath: /app/configs/
            readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: subscriber-v1

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "longrunning-hpa"
  labels:
    app: "longrunning"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "longrunning"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80