serviceName: subscriber
httpPort: 9090
grpcPort: 9080
logLevel: 1
security:
  tlsCert: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
databases:
- type: sqlDatabase
  required: true
  address: localhost:3306
  user: root
  password: hakty11
  schema: services
  metadata:
    name: sqlWrites
    dialect: mysql
    orm: gorm
externalServices:
- name: channel
  required: true
  address: localhost:8080
  tlsCert: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: account
  required: true
  address: localhost:7070
  tlsCert: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost