serviceName: subscriber
httpPort: 9090
logLevel: 1
security:
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
database:
  sqlDatabase:
    required: true
    address: localhost:3306
    user: root
    password: hakty11
    schema: services
    metadata:
      name: mysql
      dialect: mysql
      orm: gorm
externalServices:
- name: channel
  required: true
  address: localhost:8080
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: account
  required: true
  address: localhost:7070
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost