apiVersion: v1
kind: Service
metadata:
  name: emailing
  labels:
    app: emrs-emailing
spec:
  selector:
    app: emrs-emailing
  ports:
  - port: 443
    name: https

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: emrs-emailing
  labels:
    app: emrs-emailing
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emrs-emailing
      version: v1
  template:
    metadata:
      labels:
        app: emrs-emailing
        version: v1
    spec:
      containers:
      - name: emrs-emailing
        image: gidyon/emrs-emailing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
          limits:
            cpu: 1000m
            memory: 200Mi
        env:
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: host
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: port
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: password
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: symmetric-keys
              key: jwt-signing-key
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /health/ready
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 8
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 3
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /health/live
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 8
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 3
        volumeMounts:
          - name: app-tls
            mountPath: /app/secrets/keys/
            readOnly: true
          - name: app-config
            mountPath: /app/configs/
            readOnly: true
          - name: mysql-creds
            mountPath: /app/secrets/mysql/
            readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: localhost-certs
      - name: app-config
        configMap:
          name: email-v1
      - name: mysql-creds
        secret:
          secretName: mysql-creds

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "emrs-emailing-hpa"
  labels:
    app: "emrs-emailing"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "emrs-emailing"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80