package group

const (
	// PatientGroup ...
	PatientGroup = "patients_group"
	// AdminGroup ...
	AdminGroup = "admin_group"
	// SuperAdminGroup ...
	SuperAdminGroup = "super_admin_group"
	// InsuranceGroup ...
	InsuranceGroup = "insurance_group"
	// HospitalGroup ...
	HospitalGroup = "hospital_group"
)
