serviceName: Project API
httpPort: 9003
# httpOptions:
#   corsEnabled: true
logLevel: 0
security:
  tlsCert: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
  # insecure: true
databases:
  - required: true
    type: sqlDatabase
    address: localhost:3306
    user: root
    password: hakty11
    schema: services
    metadata:
      name: sqlWrites
      dialect: mysql
      orm: gorm
  - required: false
    type: redisDatabase
    address: localhost:6379
    metadata:
      name: redisReads
externalServices:
