{{- define "micro.hpa.tpl" -}}
{{- if .Values.autoscaling -}}
{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "micro.fullname" . }}
  labels:
    {{- include "micro.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "micro.fullname" . }}
  minReplicas: {{ default 1 .Values.autoscaling.minReplicas }}
  maxReplicas: {{ default 10 .Values.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ default 80 .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ default 80 .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}

{{- define "micro.hpa" -}}
{{- include "micro.util.merge" (append . "micro.hpa.tpl") -}}
{{- end -}}
