// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	call "github.com/gidyon/services/pkg/api/messaging/call"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// CallAPIClientMock is an autogenerated mock type for the CallAPIClientMock type
type CallAPIClientMock struct {
	mock.Mock
}

// Call provides a mock function with given fields: ctx, in, opts
func (_m *CallAPIClientMock) Call(ctx context.Context, in *call.CallPayload, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *emptypb.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *call.CallPayload, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *call.CallPayload, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
