serviceVersion: v1/beta
serviceName: messaging
servicePort: 9070
logging:
  level: 1
  timeFormat: 2006-01-02T15:04:05Z07:00
security:
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
databases:
  sqlDatabase:
    required: true
    address: localhost:3306
    host: localhost
    port: 3306
    user: root
    password: hakty11
    schema: services
    metadata:
      name: mysql
      dialect: mysql
      orm: gorm
  redisDatabase:
    required: true
    address: localhost:6379
    host: localhost
    port: 6379
externalServices:
- name: call
  type: Call
  required: true
  address: localhost:8080
  host: localhost
  port: 8080
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: emailing
  type: Emailing
  required: true
  address: localhost:8070
  host: localhost
  port: 8070
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: pusher
  type: Pusher
  required: true
  address: localhost:8060
  host: localhost
  port: 8060
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: sms
  type: SMS
  required: true
  address: localhost:8050
  host: localhost
  port: 8050
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: subscriber
  type: Subscriber
  required: true
  address: localhost:9060
  host: localhost
  port: 9060
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost