serviceVersion: v1/beta
serviceName: subscriber
servicePort: 9060
logging:
  level: 1
  timeFormat: 2006-01-02T15:04:05Z07:00
security:
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
databases:
  sqlDatabase:
    required: true
    address: localhost:3306
    host: localhost
    port: 3306
    user: root
    password: hakty11
    schema: services
    metadata:
      name: mysql
      dialect: mysql
      orm: gorm
  redisDatabase:
    required: false
    address: localhost:6379
    host: localhost
    port: 6379
externalServices:
- name: channel
  type: Channel
  required: true
  address: localhost:9080
  host: localhost
  port: 9080
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost
- name: account
  type: Account
  required: true
  address: localhost:9090
  host: localhost
  port: 9090
  tlsCert: /Users/jessegitaka/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  serverName: localhost