apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.config.serviceType }}
  ports:
    - port: {{ .Values.config.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.config.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
