apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-v1
  labels:
    app: sms
data:
  config.yml: |
    serviceVersion: v1/beta
    serviceName: "SMS API"
    servicePort: 80
    startupSleepSeconds: 5
    logging:
      level: -1
      timeFormat: 2006-01-02T15:04:05Z07:00
    security:
      insecure: true
---
apiVersion: v1
kind: Service
metadata:
  name: sms
  labels:
    app: sms
spec:
  selector:
    app: sms
  ports:
  - port: 80
    name: http
  - port: 8080
    name: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sms
  labels:
    app: sms
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms
      version: v1
  template:
    metadata:
      labels:
        app: sms
        version: v1
    spec:
      containers:
      - name: sms
        image: gidyon/messaging-sms:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 8080
          name: grpc
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 15Mi
          limits:
            cpu: 1000m
            memory: 200Mi
        env:
        - name: SMS_API_KEY
          valueFrom:
            secretKeyRef:
              name: sms-creds
              key: sms-api-key
        - name: SMS_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: sms-creds
              key: sms-auth-token
        - name: SMS_API_USERNAME
          valueFrom:
            secretKeyRef:
              name: sms-creds
              key: sms-api-username
        - name: SMS_API_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sms-creds
              key: sms-api-password
        - name: SMS_API_URL
          valueFrom:
            secretKeyRef:
              name: sms-creds
              key: sms-api-url
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: symmetric-keys
              key: jwt-signing-key
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /api/sms/health/ready
            port: 80
          initialDelaySeconds: 8
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 3
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /api/sms/health/live
            port: 80
          initialDelaySeconds: 8
          timeoutSeconds: 1
          periodSeconds: 20
          failureThreshold: 3
        volumeMounts:
          - name: app-config
            mountPath: /app/configs/
            readOnly: true
      volumes:
      - name: app-config
        configMap:
          name: sms-v1

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sms-hpa"
  labels:
    app: "sms"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sms"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80