serviceName: channel
httpPort: 8080
grpcPort: 8070
logLevel: 0
security:
  tlsCert: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/cert.pem
  tlsKey: /home/gideon/go/src/github.com/gidyon/services/certs/localhost/key.pem
  serverName: localhost
databases:
- type: sqlDatabase
  required: true
  address: localhost:3306
  user: root
  password: hakty11
  schema: services
  metadata:
    name: sqlWrites
    dialect: mysql
    orm: gorm
- type: sqlDatabase
  required: true
  address: localhost:3306
  user: root
  password: hakty11
  schema: services
  metadata:
    name: sqlReads
    dialect: mysql
    orm: gorm