apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- include "service.config" . | nindent 4 }}